#!/bin/bash
#SBATCH --job-name=Au_A1_fcc_dUp02
#SBATCH -o myjob.o%j
#SBATCH -e myjob.e%j
#SBATCH --nodes=1
#SBATCH --ntasks=128
#SBATCH --cpus-per-task=1
#SBATCH --time=06:00:00
#SBATCH --partition=highmem
#SBATCH --account=CHE190065

module purge
module load intel/19.0.5.281 impi/2019.5.281
module load intel-mkl hdf5 python
module list

export I_MPI_COLL_INTRANODE=pt2pt
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
PW=/anvil/projects/x-che190065/rywang/CEP-HALF/bin
runvasp="mpirun -np $SLURM_NTASKS $PW/vasp_std  > log.out"

eval $runvasp
