#!/bin/bash
#SBATCH --job-name=myjob            # job name
#SBATCH -o myjob.o%j
#SBATCH -e myjob.e%j
#SBATCH --nodes=5                  # Number of nodes
#SBATCH --ntasks-per-node=16               # Request 100 CPU cores
#SBATCH --cpus-per-task=8      # cpu-cores per task (default value is 1, >1 for multi-threaded tasks)
#SBATCH --time=96:00:00             # Job should run for up to 6 hours
#SBATCH --partition=wholenode             # queue (partition) -- normal, development, etc.
#SBATCH --account=CHE190065

#############################################################################################
# Manage processing environment, load compilers and applications.
module purge
module load intel/19.0.5.281  impi/2019.5.281
module load intel-mkl hdf5 python
module list

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
PW=/anvil/projects/x-che190065/rywang/CEP-HALF/bin
runvasp="mpirun -np $SLURM_NTASKS $PW/vasp_std  > log.out"


eval $runvasp



