#!/bin/bash
#SBATCH --job-name=PC1_s11_f089500_a2132_8x8__rough__mu-4.5871
#SBATCH -o myjob.o%j
#SBATCH -e myjob.e%j
#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --cpus-per-task=8
#SBATCH --time=23:00:00
#SBATCH --partition=standard,wholenode
#SBATCH --account=CHE190065

module purge
module load intel/19.0.5.281 impi/2019.5.281
module load intel-mkl hdf5 python

ulimit -s unlimited
export OMP_STACKSIZE=512m
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
PW=/anvil/projects/x-che190065/rywang/CEP-HALF/bin
mpirun -np $SLURM_NTASKS $PW/vasp_std > log.out
