#!/bin/bash
#SBATCH --job-name=Step-16x1_dUp02_fastcfg
#SBATCH -o myjob.o%j
#SBATCH -e myjob.e%j
#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --cpus-per-task=8
#SBATCH --time=03:00:00
#SBATCH --partition=highmem
#SBATCH --account=CHE190065

module purge
module load intel/19.0.5.281 impi/2019.5.281
module load intel-mkl hdf5 python
module list

ulimit -s unlimited
export OMP_STACKSIZE=512m
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
PW=/anvil/projects/x-che190065/rywang/CEP-HALF/bin
runvasp="mpirun -np $SLURM_NTASKS $PW/vasp_std  > log.out"

eval $runvasp
